name: Lint

on: push

jobs:
  run-linters:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint

      # note this is required for type checking
      # in part due to graphql codegen
      - name: Build All
        run: npm run prepack

      - name: Run tsc
        run: npm run tsc
